title: "iresnet_ms1m_pfe"
backbone:
    name: "iresnet50"
    learnable: false
#head:
#    name: "multilayer_perceptron"
#    in_feat: 1024
#    out_feat: 2
#    learnable: true
#    criterion:
#        name: "cross_entropy_loss"
#        mean: false
pair_classifier:
    name: "multilayer_perceptron"
    in_feat: 1024
    hidden_layers_size: [512, 512, 512, 126]
    out_feat: 2
    learnable: true
    criterion:
        name: "cross_entropy_loss"
        mean: false
optimizer:
    name: "sgd"
    lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true
scheduler:
    name: "multistep_lr"
    milestones: [1, 2, 3]
    gamma: 0.1
dataset:
    name: "ms1m"
    path: "/gpfs/gpfs0/k.fedyanin/space/ms1m/"
    batch_size: 64
    num_face_pb: 4
pretrained_backbone: /gpfs/gpfs0/k.fedyanin/space/models/backbone/ms1mv3_arcface_r50/backbone.pth
batch_size: 256
num_classes_batch: 4
is_distributed: true
iterations: 2000
epochs: 10
path_list: /gpfs/gpfs0/k.fedyanin/space/casia/list_data.txt
in_size: [112, 112]
logging:
    print_freq: 10
    save_freq: 1
evaluation_configs:
    - name: "lfw_dilemma"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/data_aligned_sphereface_repo"
    - name: "low_high_similarity"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/ldmarks.txt"
    - name: "lfw_6000_pairs"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/pairs_val_6000.txt"
      N: 6000
      n_folds: 10
